### ISSUE TITLE
Data Link not working again

### ISSUE THREAD

**Issue by tobiasstrauss** [topogram/weiboscope-data#4]
Sorry, but also http://147.8.142.179/datazip/ does not work. Could you please update a link? 

Thanks

**Comment by clemsos** [comment]
Sorry, the data source is not mine. I just wrote a script to fetch it.

You should get in touch with people maintaining the weiboscope project at
HKU. They may have moved the data somewhere else.

**Comment by clemsos** [comment]
Look at #1 for more info
